config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  get '/unvotearticle/:id', to: 'articles#unvote_for_article', as: :unvotearticle
  get '/votearticle/:id', to: 'articles#vote_for_article', as: :votearticle
  root 'categories#index'

  resources :articles
end

app/models/article.rb
class Article < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :author, class_name: 'User'
  has_many :votes

  has_many :article_categories, class_name: 'ArticleCategory'
  has_many :categories, through: :article_categories, source: :category
  accepts_nested_attributes_for :categories
  has_many :users_voted, through: :votes, source: :user

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
  validate :categories_presence

  def categories_presence
    errors.add(:categories, 'need to be selected') if categories.empty?
  end

  def self.most_voted_article
    Article.order(vote_count: :desc).first
  end

  def user_voted?(userid)
    true if users_voted.where(id: userid).first
  end

  def vote(userid)
    vote = votes.build
    vote.user_id = userid
    self.vote_count = vote_count + 1
    vote.save
  end

  def unvote(userid)
    votes.where(user_id: userid).first.destroy
    self.vote_count = vote_count - 1
  end

  def truncate_text
    body.length >= 200 ? "#{body[0..200]} ..." : "#{body} ..."
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit destroy update]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.author_id = current_user.id
    @article.category_ids = params[:article][:category_ids]
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @article
    else
      render 'new', notice: "Article's body can not be empty"
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    redirect_to articles_path, notice: 'You can only delete or edit your own articles' if @article.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :image, category_ids: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def show_articles(articles)
    content_tag :div, class: 'articles-container' do
      count = 0
      articles.collect do |article|
        votes_number = content_tag(:span, article.votes_count)
        art_vote = show_vote(article)
        author_name = content_tag(:strong, "by #{article.author.name}", class: 'article-author')
        article_author = content_tag(:div, author_name + art_vote + votes_number)
        article_title = content_tag(:div,
                                    link_to(content_tag(:h3, article.title),
                                            article_path(article),
                                            class: 'article-title chivo-regular'), class: 'd-flex a-items-center')
        article_text = content_tag(:p, article.text.truncate_words(20), class: 'article-summary')
        bg_st = "background: no-repeat center/cover url('#{rails_blob_url(article.image) if article.image.attached?}');"
        article_picture = content_tag(:div, nil, style: bg_st, class: 'article-image')
        article_category = content_tag(:h3, article.categories.take.name, class: 'articles-cat-title')
        article_info = content_tag(:div,
                                   article_category + article_title + article_author + article_text,
                                   class: 'article-preview')

        if ((count / 2) % 2).zero?
          concat(content_tag(:article,
                             article_picture + article_info, class: 'd-flex'))
        else
          concat(content_tag(:article,
                             article_picture + article_info, class: 'd-flex row-reverse'))
        end
        count += 1
      end
    end
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
 <%= render 'shared/errors', article: @article%>
 
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="form-group">
  <%= form.label :text,'Category' %>  <span>Select all that matches</span><br>
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </div>
  <div class="form-group">
    <%= form.hidden_field :author_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit class:'form-control btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |

 <%= link_to 'Back', articles_path %> 

app/views/articles/index.html.erb
 <p id="notice"><%= notice %></p>

<h1>Articles</h1>
    <div>
    <% @articles.each do |article| %>
    
        <h4><%= article.title %></td>
        <p><%= article.body %></p>
        <%= image_tag article.image_url if article.image %>
        <% if current_user.id == article.author_id %>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
    <% end %>
    </div>
    <%= link_to 'New Article', new_article_path %> 

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Image data:</strong>
  <%= image_tag @article.image_url if @article.image %>
</p>



<div class="container-fluid">
  <div class="article-wrapper">
    <%= terms %>
    <div class="info">
      <h1 class="title"><%= @article.title%></h1>
      <p class="description"><%= @article.body%></p>
      <div class="footer-info">
        <div class="author-info">
          <span>Written by : <strong><%= @article.author.username %> </strong></span>
        </div>
        
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', articles_path %>  