config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  get '/unvotearticle/:id', to: 'articles#unvote_for_article', as: :unvotearticle
  get '/votearticle/:id', to: 'articles#vote_for_article', as: :votearticle
  root 'categories#index'

  resources :articles
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :priority, presence: true
  has_many :article_categories, class_name: 'ArticleCategory'

  has_many :articles, through: :article_categories, source: :article
  has_many :latest_articles, -> { order(created_at: :desc) }, through: :article_categories, source: :article

  def self.featured_articles
    Category.includes(:articles)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper
  before_action :set_category, only: %i[show edit update destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to new_article_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @mva = Article.most_voted_article
    @categ = Category.includes(:latest_articles)
    @article = Article.all.order(created_at: :desc)
    @art = Article.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def show_categories(categories)
    content_tag :div, class: 'voted-articles' do
      article_title = content_tag(:h3, "There's no categories yet") if categories.nil?
      @categ.collect do |category|
        la = category.latest_articles.first
        if category.articles.take.nil?
          article_title = content_tag(:div, content_tag(:h3, 'No articles for this category', class: ' title'),
                                      class: 'info')
          art_picture = 'background: #4e443e'
        else
          article_title = content_tag(:div, content_tag(:h3, category.latest_articles.first.title, class: 'title'),
                                      class: 'info')
          art_picture = "height: 30vh;
           background: no-repeat center/cover url('#{la.image_url if category.latest_articles.take.image_url}') "
        end
        category_name = link_to(content_tag(:span, category.name), category_path(@categ.ids), class: 'tl-cat')

        concat(content_tag(:article,
                           (category_name + article_title),
                           style: art_picture, class: 'featured-article article'))
      end
    end
  end
end

app/views/categories/_categ.html.erb
<div class="voted-articles">
            <article class="featured-article article">
            <a href="/categories/1" > 
              <span class="tl-cat">Yatch life </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627040849/category/yatch1_foqpo9.jpg" alt="yatch image" />
              <div class="info">
                <h4 class="title">
                  Luxury Yatch
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/2" > 
              <span class="tl-cat">Fast cars </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627041146/category/1_prcdyt.jpg" alt="car image" />
              <div class="info">
                <h4 class="title">
                  Luxury cars
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/3" > 
              <span class="tl-cat">Sports </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627134382/test_app/9716ff7f535b66d8c915f2a330825c03.jpg" alt="sky sports image" />
              <div class="info">
                <h4 class="title">
                  Transfer News
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/4" > 
              <span class="tl-cat">Business </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627154416/test_app/b5f5dd44ce08d6c2583556467688e607.jpg" alt="first image" />
              <div class="info">
                <h4 class="title">
                  E-Commerce Business
                </h4>
              </div>
              </a>
            </article>

        
 <article class="featured-article article">
            <a href="/categories/5" > 
              <span class="tl-cat">Sillicon Valley  </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627134688/test_app/51a0dedeb8aeeff533e7c9250d523f19.jpg" alt="first image" />
              <div class="info">
                <h4 class="title">
                  Sillicon
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/6" > 
              <span class="tl-cat">Jet life </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627134867/test_app/99914f807f0440e35f173ec409d108af.jpg" alt="jet image" />
              <div class="info">
                <h4 class="title">
                  Luxury Jet
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/7" > 
              <span class="tl-cat">Real Estate </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627042011/category/tower_boukp4.jpg" alt="first image" />
              <div class="info">
                <h4 class="title">
                  Urban Housing
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/8" > 
              <span class="tl-cat">Africa </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627042015/category/Africa_l9sszp.jpg" alt="first image" />
              <div class="info">
                <h4 class="title">
                  Africa Unites
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/9" > 
              <span class="tl-cat">Fashion </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627042013/category/fashion_osptlg.jpg" alt="first image" />
              <div class="info">
                <h4 class="title">
                  Fashion Designers
                </h4>
              </div>
              </a>
            </article>

            <article class="featured-article article">
            <a href="/categories/10" > 
              <span class="tl-cat">Motor Bike </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1626968093/test_app/57d39866e060008b81fcf97ec6c0a59e.webp" alt="bike image" />
              <div class="info">
                <h4 class="title">
                  Best Motor Bike 2021
                </h4>
              </div>
              </a>
            </article>
            <article class="featured-article article">
            <a href="/categories/11" > 
              <span class="tl-cat">Politics </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627042501/category/obama_r9wj7e.jpg" alt="bike image" />
              <div class="info">
                <h4 class="title">
                  Obama
                </h4>
              </div>
              </a>
            </article>
            <article class="featured-article article">
            <a href="/categories/12" > 
              <span class="tl-cat">Movie </span>
              <img class="img-responsive" src="https://res.cloudinary.com/dd6iakosn/image/upload/v1627297734/test_app/movieposter_en_qj2egn.jpg" alt="bike image" />
              <div class="info">
                <h4 class="title">
                  Central Intelligence
                </h4>
              </div>
              </a>
            </article> 
    </div>

app/views/categories/_form.html.erb
<%= form_with model: category, url:categories_path do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>
<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container-fluid">
  <div class="row">
  <article class="col-sm-12 article featured-article hero-article">
      <span class="tl-cat">FEATURED ARTICLE</span>
      <img class="img-responsive" src="<%= image %>" alt=" image" />
      <div class="info">
        <h1 class="title"> <%= body %> </h1>
        <p class="description"><%= title %></p>
      </div>
    </article>
  </div>
  <%= render "categories/categ" %>






    
       

app/views/categories/new.html.erb
<h1>New Categories</h1>
<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% rev = false %>
<div class="container-fluid category-page">
  <div class="voted-articles">
  <% @category.articles.order(created_at: :desc).each_with_index do |art,i| %>
    <article class="featured-article article">
      <img class="img-responsive <%=rev ? 'image-reversed' : '' %>" src="<%= art.image ? art.image_url : "https://www.usanetwork.com/sites/usanetwork/files/2019/07/Suits_S9-KeyArt-Show-Tile-1920x1080.jpg" %>"  alt="suits image" />
      <div class="information <%=rev ? 'information-reversed' : '' %>">
        <span class="cat"><%= @category.name%> </span>
        <h4 class="title">
          <%= art.title %>
        </h4>
        <p class="description">
          <%= art.truncate_text %>
        </p>
        <div class="actions">
          <div>
            <%= link_to 'View full &#8594;'.html_safe, article_path(art.id)  %>
          </div>
          <div class="votes-wrapper">
          <p>Votes</p>
            <% voted = current_user && art.user_voted?(current_user.id) %>
            <%= link_to voted ? unvotearticle_path(art.id) : votearticle_path(art.id), class:'vote-btn' do %>
              <%= image_tag voted ? 'vote.png': 'vote.png' %>
            <% end %>
            <span><%= art.vote_count if art.vote_count && art.vote_count > 0 %></span>
          </div>
        </div>
      </div>
    </article>
    <% rev = !rev if (i+1).even? %>
    <% end %>
  </div>
</div>