config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  get '/unvotearticle/:id', to: 'articles#unvote_for_article', as: :unvotearticle
  get '/votearticle/:id', to: 'articles#vote_for_article', as: :votearticle
  root 'categories#index'

  resources :articles
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert <%= name %> alert-dismissible fade show" role="alert">
    <%= content_tag :strong, msg.html_safe %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="main-nav">
    <%= link_to root_path, class: 'navbar-brand' do %>
         <h1 style="margin:0 ;color: rgba(0,0,0, 0.3); font-family: 'Helvetica Neue', sans-serif; font-size: 30px; font-weight: bold; letter-spacing: -1px; line-height: 1; text-align: center;"> LuXuryLyF</h1>
    <% end %>
    <ul class="nav navbar-nav">
      <li class="nav-item"> <a href="#" class="policy-links">Privacy Policy</a> </li>
      <li class="nav-item"> <a href="#" class="policy-links">Terms &amp; Conditions</a> </li>
      <li class="nav-item"> <a href="https://www.linkedin.com/in/fortunatus-ihedoro/" >&copy; Copyright 2021. All rights reserved.</a> </li>
    </ul>
    
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="main-nav">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <h1 style="margin:0 ;color: #111; font-family: 'Helvetica Neue', sans-serif; font-size: 30px; font-weight: bold; letter-spacing: -1px; line-height: 1; text-align: center;"><%#= image_tag('logo.jpg', style: 'width:50px')%> LuXuryLyF</h1>
  <% end %>

  <ul class="nav navbar-nav articles-categories">
    <li class="nav-item"> <%= link_to 'Home', root_path %> </li>
  
 <li class="nav-item"> <%= link_to 'New Category', new_category_path %> </li> 


    <li class="nav-item"> <%= link_to 'New Article', new_article_path %> </li>
  </ul>
  <ul class="nav navbar-nav">
   

    
    <% if user_signed_in? %>
    <li> <%= link_to current_user.username %> </li>
      <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete%> </li>
      <% else %>
      <li> <%= link_to 'Login', new_user_session_path %> </li>
      <li><a href="#">|</a></li>
      <li><%= link_to 'Register', new_user_registration_path %> </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifestyleArticle</title>
    <link rel="icon" href="https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fyacht&psig=AOvVaw2YYxGYd1TdhWKuTDMIrsEu&ust=1626957110398000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJiij9eV9PECFQAAAAAdAAAAABAD" type="image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <%= render 'layouts/header'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>